# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a5b46a961b7e48237c33abfe4c72a533128ab15376191f20aa2a7dec6c32592f94231d2eb3eb2f785a674fa32cd064f44c683bfd97bddef206cddd89eb4829c

test:
  secret_key_base: 07c538123dcc849eea59b3f069654898325aef8f0864c9d5310ccb632b1e225980f7e3826f069ec500e40d9e3073247500abc75cae7c96bbbb8cbbf45e5b43a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
